### PR TITLE
Background color classes

### PR DESCRIPTION
**Pull request by kevin-pauls**
added the background color classes for the trans shades 80-20. Left out the others.

### CODE REVIEW

**Comment by kevin-pauls** [comment]
Not sure if you were wanting ALL of the bg color classes added but we can add them again later. I figured we don't need all of them as it will add "extra" that may not be needed for the framework.

**Comment by kevingeary** [comment]
Sorry, I should have been more specific. I think the lightness variants are more necessary than the opacity variants for bg colors.

**Comment by kevin-pauls** [comment]
kk i'll change it to include the others and exclude the transparent classes

**Comment by kevin-pauls** [comment]
nvm I see someone has submitted all of them!

**Pull request closed without merging**
